Tidy up build and leverage new slamdata commons dependencies
slamdata/scala-abt pull request #6
Opened 2017-02-25 19:41 UTC by wemrysi

Makes use of the new `slamdata-sbt` and predef and generally brings the build structure up to date.

When merging, just use the GH merge button for this PR as the previous version included a "SNAPSHOT" suffix which I'm not sure the merge script can handle, we should be able to use it going forward.

2017-02-25 19:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slamdata/scala-abt?pullRequest=6) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slamdata/scala-abt?pullRequest=6) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slamdata/scala-abt?pullRequest=6) it.</sub>

2017-02-25 20:31 UTC, sellout requested changes
Very excited to see this updated.

2017-02-25 20:31 UTC, sellout commented on .travis.yml
> +  - oraclejdk8
I think you should still build on 7 as well, and exclude the 2.12/jdk7 combo.

2017-02-25 20:31 UTC, sellout commented on core/src/main/scala/abt/Arity.scala
> +import slamdata.Predef.Vector
Should just use `slamdata.Predef._`.

2017-02-25 20:31 UTC, sellout commented on core/src/main/scala/abt/Coord.scala
> +import slamdata.Predef.Int
Same.

2017-02-25 20:31 UTC, sellout commented on core/src/main/scala/abt/View.scala
> +import slamdata.Predef.Vector
Same.

2017-02-27 14:42 UTC, wemrysi commented
@sellout Thanks for the feedback, updated.

2017-02-27 14:43 UTC, sellout approved these changes

2017-02-27 17:42 UTC, drostron approved these changes
👍🏾

2017-02-27 17:43 UTC, merged